name: Setup sphinx
description: Download and install Sphinx.

runs:
  using: composite
  steps:
  - name: Install sphinx
    run: sudo pip install -r "$GITHUB_ACTION_PATH/requirements.txt"
    shell: bash
