name: Setup spark
description: Download and install Spark, the CodeQL docs tool.

inputs:
  spark-version:
    description: spark version number
    required: true

runs:
  using: composite
  steps:
  - name: Install libpcre3
    run: sudo apt install libpcre16-3 libpcre3 libpcre3-dev libpcre32-3 libpcrecpp0v5
    shell: bash

  - name: Download spark
    uses: ./.github/actions/get-workflow-artifact
    with:
      token: ${{ secrets.CODEQL_CI_TOKEN }} # TODO: Replace with another PAT with access to github/codeql-spark if needed.
      repo: github/codeql-spark
      workflow: build.yml
      artifact-name: spark-Linux-X64
