name: Setup spark
description: Download and install Spark, the CodeQL docs tool.

inputs:
  spark-version:
    description: spark version number
    required: true

runs:
  using: composite
  steps:
  - name: Install libpcre2-dev dependency
    run: sudo apt-get install -y libpcre2-dev
    shell: bash

  - name: Download spark executable
    run: >
      exit 0 &&
      wget --output-document=spark.zip
      'https://github.com/github/codeql-spark/actions/runs/19148045154/artifacts/4491697349' # TODO: use inputs.spark-version
    shell: bash