name: Setup spark
description: Download and install Spark, the CodeQL docs tool.

inputs:
  spark-version:
    description: spark version number
    required: true

runs:
  using: composite
  steps:
  - name: Install libpcre3
    run: sudo apt install libpcre16-3 libpcre3 libpcre3-dev libpcre32-3 libpcrecpp0v5
    shell: bash

  - name: Download spark executable
    run: >
      wget --output-document=spark.zip
      'https://github.com/dsp-testing/mario-campos-docs-workflow/releases/download/v${{ inputs.spark-version }}/spark-Linux-X64.zip'
    shell: bash
    working-directory: ${{ runner.temp }}
  
  - name: Unzip spark executable
    run: unzip spark.zip -d "$GITHUB_WORKSPACE"
    shell: bash
    working-directory: ${{ runner.temp }}
